# Site wide configuration

title: Luiz Folksilva
locale: pt_BR
description: Aprendizado, Desenvolvimento e Produtividade de um jeito fácil.
logo: site-logo.png
search: true
#url: //folksilva.github.io
url: //folksilva.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Luiz Folksilva
  avatar: bio-photo.png
  email: folksilva@gmail.com
  disqus-shortname: folksilva
  twitter: folksilva
  facebook: folksilva
  github: folksilva
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: folksilva
  instagram: folksilva
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: folksilva
    analytics: UA-37784371-2
    verify: VPnR4s_lMI5nM0k-NAHt0yjYviXLeXK6X1mOIFYWomw
    ad-client:
    ad-slot:
  bing-verify:
